spring:
  application:
    name: kylin-gateway
  jmx:
    enabled: false
  cloud:
    gateway:
      httpclient:
        connectTimeout: 3000
        responseTimeout: 480000

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG

server:
  tomcat:
    basedir: ./
    accesslog:
      enabled: true
      buffered: true
      directory: logs
      file-date-format: .yyyy-MM-dd
      pattern: "%h %l %u %t \"%r\" %s %b %D %{User-Agent}i"
      rotate: true
      rename-on-rotate: false
      prefix: access_log
      suffix: .log

kylin:
  gateway:
    route-table:
      refresh-cron: 0/3 * * * * *
    ke:
      version: 3x
    health:
      rest-template:
        connect-timeout: 5000
        read-timeout: 5000
      ping-strategy:
        retry-times: 3
        interval-seconds: 5
    datasource:
      type: file
      route-table-file-path: ${gateway.home}/conf/route_table
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://10.3.1.17:3306/leotest
      username: root
      password: passw0rd
      table-name: km_route_table

management.endpoints.web.exposure.include: health, gateway

server.port: 7777