USER-SERVER:
  ribbon:
    listOfServers: 10.1.2.166:7070
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule

spring:
  jmx:
    enabled: false
  cloud:
    gateway:
      routes:
      - id: kylin
        uri: lb://USER-SERVER
        order: 9000
        predicates:
        - Kylin=p1,p2
      - id: default
        uri: lb://USER-SERVER
        order: 22333
        predicates:
        - Path=/**


logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG

server:
  tomcat:
    basedir: ./
    accesslog:
      enabled: true
      buffered: true
      directory: logs
      file-date-format: .yyyy-MM-dd
      pattern: "%h %l %u %t \"%r\" %s %b %D %{User-Agent}i"
      rotate: true
      rename-on-rotate: false
      prefix: access_log
      suffix: .log

management.endpoints.web.exposure.include: health,gateway

kylin:
  gateway:
    ke:
      version: 3x

server.port: 7777