spring:
  jmx:
    enabled: false
  cloud:
    gateway:
      httpclient:
        connectTimeout: 3000
        responseTimeout: 480000

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG

server:
  tomcat:
    basedir: ./
    accesslog:
      enabled: true
      buffered: true
      directory: logs
      file-date-format: .yyyy-MM-dd
      pattern: "%h %l %u %t \"%r\" %s %b %D %{User-Agent}i"
      rotate: true
      rename-on-rotate: false
      prefix: access_log
      suffix: .log

management.endpoints.web.exposure.include: health,gateway

kylin:
  gateway:
    route-table:
      refresh-cron: 0/30 * * * * *
    ke:
      version: 3x

server.port: 7777